# Task_9_Ekin_Viacheslaw

import turtle

turtle.pensize(2)
turtle.pencolor("white")


turtle.home()
turtle.up()
turtle.fillcolor("green")
turtle.begin_fill()
turtle.right(90)
turtle.forward(100)
turtle.down()
turtle.right(140)
turtle.forward(100)
turtle.right(180)
turtle.forward(100)
turtle.right(100)
turtle.forward(100)
turtle.up()
turtle.home()
turtle.down()
turtle.left(180)
turtle.circle(100, 120)
turtle.end_fill()
turtle.up()
turtle.home()

turtle.down()
turtle.begin_fill()
turtle.right(90)
turtle.forward(100)
turtle.right(140)
turtle.forward(100)
turtle.up()
turtle.home()
turtle.down()
turtle.fillcolor("blue")
turtle.left(180)
turtle.circle(100, 40)
turtle.end_fill()
turtle.up()

turtle.done()